spring.application.name=aviasales
spring.config.import=optional:file:.env[.properties]

# H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:AviasalesDatabase
spring.datasource.username=sava
spring.datasource.password=

# --- PostgreSQL ---
#spring.datasource.url=jdbc:postgresql://localhost:55300/aviasales
#spring.datasource.username=postgres
#spring.datasource.password=your_password
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/aviasales}
spring.data.mongodb.auto-index-creation=${APP_MONGO_AUTO_INDEX_CREATION:false}

# App Mongo settings
app.mongo.enabled=${APP_MONGO_ENABLED:false}
app.mongo.flight-cache-ttl-minutes=15
app.mongo.retry-after=${APP_MONGO_RETRY_AFTER:30s}

# Payment window
payments.booking-payment-ttl=${PAYMENTS_BOOKING_PAYMENT_TTL:15s}

# Mail
app.mail.enabled=${APP_MAIL_ENABLED:true}
app.mail.from=${APP_MAIL_FROM:no-reply@aviasales.local}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# External flight import (GET /flights-all from another service)
app.flight-import.enabled=false
app.flight-import.base-url=
app.flight-import.path=/flights-all

# CSV
app.flightdata.csv-path=classpath:data/flights.csv
app.flightdata.csv-enabled=true