spring.application.name=aviasales

# H2
spring.h2.console.enabled = true
spring.datasource.url = jdbc:h2:mem:AviasalesDatabase
spring.datasource.username = sava
spring.datasource.password =

# --- Spring Mail (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- App mail settings ---
app.mail.from=${GMAIL_USERNAME}


spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.hibernate.ddl-auto=update

payments.booking-payment-ttl=15s