spring.application.name=aviasales

# H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:AviasalesDatabase
spring.datasource.username=sava
spring.datasource.password=

# --- PostgreSQL ---
#spring.datasource.url=jdbc:postgresql://localhost:55300/aviasales
#spring.datasource.username=postgres
#spring.datasource.password=your_password
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/aviasales}
spring.data.mongodb.auto-index-creation=true

# App Mongo settings
app.mongo.flight-cache-ttl-minutes=15
